name: ⚙️ Run Unit Tests


on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      name: Checkout code

    - uses: actions/cache@v4
      with:
        path: |
          ~/.cache/pip
          ~/.platformio/.cache
        key: ${{ runner.os }}-pio

    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Install PlatformIO Core
      run: pip install --upgrade platformio

      # Copy USER_SECRETS.TEMPLATE.h to USER_SECRETS.h
    - name: Copy USER_SECRETS.TEMPLATE.h to USER_SECRETS.h
      run: cp ./Software/USER_SECRETS.TEMPLATE.h ./Software/USER_SECRETS.h

    - name: Run Unit Tests
      run: pio remote --agent lilygo test -e test -r
      continue-on-error: true
      env:
        PLATFORMIO_AUTH_TOKEN: ${{ secrets.PLATFORMIO_AUTH_TOKEN }}